# Exclude files from Jekyll build
exclude:
    - README.md
    - LICENSE
    - CNAME
    - Gemfile
    - Gemfile.lock
    - vendor
    
# Installed gems
plugins: 
    - jekyll-target-blank
    - jekyll-redirect-from

# Gem settings

# Css
css: "/style.css"


# Site settings
encoding: utf-8
lang: en-GB
title: "Understanding and Building a Rainfall-Runoff Model"
logo: "/assets/img/logos/logo_hex.svg"
description: "A step-by-step tutorial on how to build a Rainfall-Runoff Model in R"
baseurl: ""
url: "https://eddatascienceees.github.io/tutorial-hollybee04/"
repo: "https://github.com/EdDataScienceEES/tutorial-hollybee04.git"
email: "s2345560@ed.ac.uk"
google_analytics: UA-92956541-1
css_inline: false 
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true 

# Favicons
favicons: 
    16: '/assets/img/logos/logo_hex@16px.png'
    32: '/assets/img/logos/logo_hex@32px.png'
    64: '/assets/img/logos/logo_hex@64px.png'
    128: '/assets/img/logos/logo_hex@128px.png'
    256: '/assets/img/logos/logo_hex@256px.png'
    512: '/assets/img/logos/logo_hex@512px.png'
    1024: '/assets/img/logos/logo_hex@1024px.png'

# Site navigation
navigation_header:
- title: Home
  url: /
- title: Tutorials
  url: /tutorials.html

# Define collections
collections:
    tutorials:
        output: true
        permalink: /tutorials/:path/
    course:
        output: true
        permalink: /course/:path/
    DL:
        output: true
        permalink: /DL/:path/
    posts:
        output: true
        permalink: /posts/:path/

# Theme setting
theme: jekyll-theme-minimal

