# Exclude files from Jekyll build
exclude:
    - README.md
    - LICENSE
    - CNAME
    - Gemfile
    - Gemfile.lock
    - vendor

# Installed gems
plugins: 
    - jekyll-target-blank
    - jekyll-redirect-from
 
# Gem settings

# Site settings
encoding: utf-8
lang: en-GB
title: "Understanding and Building a Rainfall-Runoff Model"
description: "A tutorial on hydrological modelling"
baseurl: ""
url: "https://eddatascienceees.github.io/tutorial-hollybee04/"
repo: "https://github.com/EdDataScienceEES/tutorial-hollybee04.git"
email: "s2345560@ed.ac.uk"
google_analytics: UA-92956541-1
css_inline: false 
description: "A step-by-step tutorial on how to build a Rainfall-Runoff Model in R"
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true 

# Site navigation
navigation_header:
- title: Home
  url: /
- title: Tutorials
  url: /tutorials.html

# Define collections
collections:
    tutorials:
        output: true
        permalink: /tutorials/:path/
    course:
        output: true
        permalink: /course/:path/
    DL:
        output: true
        permalink: /DL/:path/
    posts:
        output: true
        permalink: /posts/:path/
theme: jekyll-theme-slate
